FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy server file
COPY flask_server.py .

# Expose Flask port
EXPOSE 8484

# Run server
CMD ["python", "flask_server.py"]
